name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: mount bazel cache
      uses: actions/cache@v2
      with:
        key: bazel
        path: ~/.cache/bazel

    - name: install bazelisk
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        curl -fLo "${GITHUB_WORKSPACE}/bin/bazel" "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --config=linux //...
