name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: bazel test
        uses: ngalaiko/bazel-action/1.2.1@master
        with:
          args: test --cxxopt=-std=c++17 ...
